function(engine_apply_compiler_options target_name)
    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /permissive- /fp:precise)
    else()
        target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math)
    endif()
endfunction()
